INSERT INTO courses (course_id, course_name, credit_hours) VALUES
('CSCI', 1000,'Computer Science as a Field of Work and Study', 1),
('CSCI', 1300,'Introduction to Programming', 4),
('CSCI', 1200,'Introduction to computational thinking', 3),
('CSCI', 2270,'Data Structures', 4),
('CSCI', 2400,'Computer Systems', 4),
('CSCI', 3308,'Software Development Methods and Tools', 3),
('CSCI', 2824,'Discrete Structures', 3),
('CSCI', 3104,'Algorithms', 4),
('CSCI', 3155,'Principles of Programming Languages', 4),
('CSCI', 3287,'Design and Analysis of Database systems', 3),
('CSCI', 3753,'Design and Analysis of Operating systems', 4),
('CSCI', 2820,'Linear Algebra with Computer Science Applications', 3),
('CSCI', 3202,'Introduction to Artificial Intelligence', 3),
('CSCI', 3022,'Introduction to Data Science', 3),
('CSCI', 3002,'Fundamentals of Human Computer Interaction', 4),
('CSCI', 3010,'Intensive Programming Workshop', 3),
('CSCI', 4253,'Data Center Scale Computing', 3),
('CSCI', 4273,'Network Systems', 3),
('CSCI', 4308,'Software Engineering Project 1', 4),
('CSCI', 4448,'Object-Oriented Analysis and Design', 3),
('CSCI', 4502,'Data Mining', 3);