INSERT INTO users (username, password) VALUES 
('asd', '$2b$10$X9I23OjqzTuXLV4WwaGnWepuR0myejQycSlg0sBcPPRKAVi2hKUzq'); --username is asd, password is asd

INSERT INTO courses (course_prefix, course_id, course_name, credit_hours) VALUES 
('CSCI', 1000,'Computer Science as a Field of Work and Study', 1),
('CSCI', 1300,'Introduction to Programming', 4),
('CSCI', 1200,'Introduction to computational thinking', 3),
('CSCI', 2270,'Data Structures', 4),
('CSCI', 2400,'Computer Systems', 4),
('CSCI', 3308,'Software Development Methods and Tools', 3),
('CSCI', 2824,'Discrete Structures', 3),
('CSCI', 3104,'Algorithms', 4),
('CSCI', 3155,'Principles of Programming Languages', 4),
('CSCI', 3287,'Design and Analysis of Database systems', 3),
('CSCI', 3753,'Design and Analysis of Operating systems', 4),
('CSCI', 2820,'Linear Algebra with Computer Science Applications', 3),
('CSCI', 3202,'Introduction to Artificial Intelligence', 3),
('CSCI', 3022,'Introduction to Data Science', 3),
('CSCI', 3002,'Fundamentals of Human Computer Interaction', 4),
('CSCI', 3010,'Intensive Programming Workshop', 3),
('CSCI', 4253,'Data Center Scale Computing', 3),
('CSCI', 4273,'Network Systems', 3),
('CSCI', 4308,'Software Engineering Project 1', 4),
('CSCI', 4448,'Object-Oriented Analysis and Design', 3),
('CSCI', 4502,'Data Mining', 3),

('ASEN', 1000, 'Introduction to Aerospace Engineering Sciences', 1),
('ASEN', 1009, 'Undergraduate Aerospace Seminar', 1),
('ASEN', 1022, 'Materials Science for Aerospace Engineers', 3),
('ASEN', 1320, 'Aerospace Computing and Engineering Applications', 4),
('ASEN', 1400, 'Gateway to Space', 3),
('ASEN', 1403, 'Introduction to Rocket Engineering', 3),
('ASEN', 1969, 'Pathway to Space', 3),
('ASEN', 2001, 'Aerospace 1: Introduction to Statics, Structures, and Materials', 4),
('ASEN', 2002, 'Aerospace 2: Introduction to Thermodynamics and Aerodynamics', 4),
('ASEN', 2012, 'Experimental and Computational Methods in Aerospace Engineering Sciences', 2),
('ASEN', 2519, 'Special Topics', 3),
('ASEN', 2701, 'Introduction to Statics, Structures, and Materials', 3),
('ASEN', 2702, 'Introduction to Thermodynamics and Aerodynamics', 3),
('ASEN', 2703, 'Introduction to Dynamics and Systems', 3),
('ASEN', 2704, 'Introduction to Aerospace Vehicle Design and Performance', 3),
('ASEN', 2802, 'Aerospace Sciences Lab I', 1),
('ASEN', 2803, 'Dynamics and Controls Lab', 1),
('ASEN', 2804, 'Aerospace Vehicle Design Lab', 2),
('ASEN', 2849, 'Independent Study', 3),
('ASEN', 3036, 'Introduction to Human Spaceflight', 3),
('ASEN', 3046, 'Introduction to Humans in Aviation', 3),
('ASEN', 3111, 'Aerodynamics', 4),
('ASEN', 3112, 'Structures', 4),
('ASEN', 3113, 'Thermodynamics and Heat Transfer', 4),
('ASEN', 3128, 'Aircraft Dynamics', 3),
('ASEN', 3200, 'Orbital Mechanics/Attitude Dynamics and Control', 4),
('ASEN', 3300, 'Aerospace Electronics and Communications', 4),
('ASEN', 3519, 'Special Topics', 3),
('ASEN', 3700, 'Orbital Mechanics/Attitude Dynamics and Control', 3),
('ASEN', 3711, 'Aerodynamics', 3),
('ASEN', 3712, 'Structures', 3),
('ASEN', 3713, 'Thermodynamics and Heat Transfer', 3),
('ASEN', 3728, 'Aircraft Dynamics', 3),
('ASEN', 3801, 'Aerospace Vehicles Dynamics and Controls Lab', 1),
('ASEN', 3802, 'Aerospace Sciences Lab II', 1),
('ASEN', 3930, 'Aerospace Engineering Cooperative Education', 6),
('ASEN', 4013, 'Foundations of Propulsion', 3),
('ASEN', 4018, 'Senior Projects 1: Design Synthesis', 4),
('ASEN', 4028, 'Senior Projects 2: Design Practicum', 4),
('ASEN', 4057, 'Aerospace Software', 3),
('ASEN', 4067, 'Microavionics: Introduction to PIC Microcontrollers for Aerospace Systems', 3),
('ASEN', 4090, 'Global Positioning Systems Applications', 3),
('ASEN', 4114, 'Automatic Control Systems', 3),
('ASEN', 4123, 'Vibration Analysis', 3),
('ASEN', 4128, 'Human Factors in Engineering and Design', 3),
('ASEN', 4138, 'Aircraft Design', 3),
('ASEN', 4218, 'Large Space Structures Design', 3),
('ASEN', 4338, 'Computer Analysis of Structures', 3),
('ASEN', 5007, 'Introduction to Finite Elements', 3),
('ASEN', 5010, 'Spacecraft Attitude Dynamics and Control', 3),
('ASEN', 5012, 'Mechanics of Aerospace Structures', 3),
('ASEN', 5014, 'Linear Control Systems', 3),
('ASEN', 5016, 'Space Life Sciences', 3),
('ASEN', 5018, 'Graduate Projects I', 3),
('ASEN', 5022, 'Dynamics of Aerospace Structures', 3),
('ASEN', 5034, 'Stochastic Methods for Systems Engineering', 3),
('ASEN', 5044, 'Statistical Estimation for Dynamical Systems', 3),
('ASEN', 5047, 'Probability and Statistics for Aerospace Engineering Sciences', 3),
('ASEN', 5050, 'Space Flight Dynamics', 3),
('ASEN', 5051, 'Fundamentals of Fluid Dynamics', 3),
('ASEN', 5052, 'Analytical Astrodynamics', 3),
('ASEN', 5053, 'Rocket and Spacecraft Propulsion', 3),
('ASEN', 5063, 'Aircraft Propulsion', 3),
('ASEN', 5067, 'Microavionics: Introduction to PIC Microcontrollers for Aerospace Systems', 3),
('ASEN', 5090, 'Introduction to Global Navigation Satellite Systems', 3),
('ASEN', 5098, 'System Engr and Design', 3),
('ASEN', 5111, 'Introduction to Aeroelasticity', 3),
('ASEN', 5114, 'Automatic Control Systems', 3),
('ASEN', 5121, 'Boundary Layers and Convection', 3),
('ASEN', 5122, 'Control of Aerospace Structures 1', 3),
('ASEN', 5148, 'Spacecraft Design', 3),
('ASEN', 5151, 'Fundamentals of Gas Dynamics', 3),
('ASEN', 5158, 'Space Habitat Design', 3),
('ASEN', 5168, 'Remote Sensing Instrumentation Design', 3),
('ASEN', 5188, 'Fundamentals of Systems Engineering', 3),
('ASEN', 5210, 'Remote Sensing Seminar', 1),
('ASEN', 5212, 'Composite Structures and Materials', 3),
('ASEN', 5218, 'Large Space Structures Design', 3),
('ASEN', 5222, 'Materials Science for Composite Manufacturing', 3),
('ASEN', 5227, 'Mathematics for Aerospace Engineering', 3),
('ASEN', 5235, 'Introduction to Atmospheric Radiative Transfer and Remote Sensing', 3),
('ASEN', 5245, 'Radar and Remote Sensing', 3),
('ASEN', 5254, 'Algorithmic Motion Planning', 3),
('ASEN', 5264, 'Decision Making under Uncertainty', 3),
('ASEN', 5307, 'Engineering Data Analysis Methods', 3),
('ASEN', 5321, 'Computational Fluid Dynamics Structured Grid', 3),
('ASEN', 5325, 'Small Scale Processes in Geophysical Fluids', 3),
('ASEN', 5335, 'Aerospace Environment', 3),
('ASEN', 5347, 'Math Methods in Dynamics', 3),
('ASEN', 5417, 'Numerical Methods in Engineering and Science', 3),
('ASEN', 5426, 'Neural Systems and Physiological Control', 3),
('ASEN', 5440, 'Mission Design and Development for Space Sciences', 3),
('ASEN', 5550, 'Designing for Defense', 3),
('ASEN', 6008, 'Interplanetary Mission Design', 3),
('ASEN', 6010, 'Advanced Spacecraft Dynamics and Control', 3),
('ASEN', 6011, 'Experimental Fluid Mechanics', 3),
('ASEN', 6013, 'High Speed Propulsion', 3),
('ASEN', 6014, 'Spacecraft Formation Flying', 3),
('ASEN', 6015, 'Space Vehicle Guidance and Control', 3),
('ASEN', 6020, 'Optimal Trajectories', 3),
('ASEN', 6021, 'Viscous Flow', 3),
('ASEN', 6024, 'Nonlinear Control Systems', 3),
('ASEN', 6028, 'Graduate Projects II', 3),
('ASEN', 6037, 'Turbulent Flows', 3),
('ASEN', 6050, 'Space Instrumentation', 3),
('ASEN', 6055, 'Data Assimilation & Inverse Methods for Earth & Geospace Observations', 3),
('ASEN', 6060, 'Advanced Astrodynamics', 3),
('ASEN', 6061, 'Molecular Gas Dynamics and DSMC', 3),
('ASEN', 6070, 'Satellite Geodesy', 3),
('ASEN', 6080, 'Statistical Orbit Determination', 3),
('ASEN', 6084, 'Optical Multi-Target Tracking', 3),
('ASEN', 6090, 'Advanced Global Navigation Satellite Systems: Software and Applications', 3),
('ASEN', 6091, 'Global Navigation Satellite System (GNSS) Receiver Architecture', 3),
('ASEN', 6107, 'Nonlinear Finite Element Methods', 3),
('ASEN', 6116, 'Spacecraft Life Support Systems', 3),
('ASEN', 6216, 'Human Operation of Aerospace Vehicles', 3),
('ASEN', 6265, 'Fundamentals of Spectroscopy for Optical Remote Sensing', 3),
('ASEN', 6331, 'Computational Fluid Dynamics', 3),
('ASEN', 6337, 'Remote Sensing Data Analysis', 3),
('ASEN', 6365, 'Lidar Remote Sensing', 3),
('ASEN', 6367, 'Advanced Finite Element Methods for Plates, Shells, and Solids', 3),
('ASEN', 6412, 'Uncertainty Quantification', 3),
('ASEN', 6427, 'Advanced Computational Fluid Dynamics', 3),
('ASEN', 6517, 'Computational Methods In Dynamics', 3),
('ASEN', 6800, 'Master of Engr Project', 3),

('APPM', 1235, 'Pre-Calculus for Engineers', 4),
('APPM', 1236, 'Precalculus Work Group', 1),
('APPM', 1340, 'Calculus 1 with Algebra, Part A', 4),
('APPM', 1345, 'Calculus 1 with Algebra, Part B', 4),
('APPM', 1350, 'Calculus 1 for Engineers', 4),
('APPM', 1351, 'Calculus 1 Work Group', 1),
('APPM', 1360, 'Calculus 2 for Engineers', 4),
('APPM', 1361, 'Calculus 2 Work Group', 1),
('APPM', 1390, 'A Game for Calculus', 1),
('APPM', 1650, 'Python for Mathematical and Statistical Applications', 4),
('APPM', 2340, 'Calculus 3 for Statistics and Data Science', 4),
('APPM', 2350, 'Calculus 3 for Engineers', 4),
('APPM', 2351, 'Calculus 3 Work Group', 1),
('APPM', 2360, 'Introduction to Differential Equations with Linear Algebra', 4),
('APPM', 2450, 'Calculus 3 Computer Lab', 1),
('APPM', 2460, 'Differential Equations Computer Lab', 1),
('APPM', 2750, 'Java: Training, Mathematical Algorithms, and Mobile Apps', 4),
('APPM', 3010, 'Chaos in Dynamical Systems', 3),
('APPM', 3050, 'Scientific Computing in Matlab', 3),
('APPM', 3170, 'Discrete Applied Mathematics', 3),
('APPM', 3310, 'Matrix Methods and Applications', 3),
('APPM', 3350, 'Advanced Engineering Calculus', 3),
('APPM', 3570, 'Applied Probability', 3),
('APPM', 4120, 'Introduction to Operations Research', 3),
('APPM', 4320, 'Introduction to Dynamics on Networks', 3),
('APPM', 4350, 'Methods in Applied Mathematics: Fourier Series and Boundary Value Problems', 3),
('APPM', 4360, 'Methods in Applied Mathematics: Complex Variables and Applications', 3),
('APPM', 4370, 'Computational Neuroscience', 3),
('APPM', 4380, 'Modeling in Applied Mathematics', 3),
('APPM', 4390, 'Modeling in Mathematical Biology', 3),
('APPM', 4440, 'Undergraduate Applied Analysis 1', 3),
('APPM', 4450, 'Undergraduate Applied Analysis 2', 3),
('APPM', 4490, 'Theory of Machine Learning', 3),
('APPM', 4510, 'Data Assimilation in High Dimensional Dynamical Systems', 3),
('APPM', 4515, 'High-Dimensional Probability for Data Science', 3),
('APPM', 4530, 'Stochastic Analysis for Finance', 3),
('APPM', 4560, 'Markov Processes, Queues, and Monte Carlo Simulations', 3),
('APPM', 4565, 'Random Graphs', 3),
('APPM', 4570, 'Statistical Methods', 3),
('APPM', 4590, 'Statistical Modeling', 3),
('APPM', 4600, 'Numerical Methods and Scientific Computing', 4),
('APPM', 4610, 'Numerical Differential Equations', 3),
('APPM', 4650, 'Intermediate Numerical Analysis 1', 3),
('APPM', 4660, 'Intermediate Numerical Analysis 2', 3),
('APPM', 5120, 'Introduction to Operations Research', 3),
('APPM', 5320, 'Introduction to Dynamics on Networks', 3),
('APPM', 5350, 'Methods in Applied Mathematics: Fourier Series and Boundary Value Problems', 3),
('APPM', 5360, 'Methods in Applied Mathematics: Complex Variables and Applications', 3),
('APPM', 5370, 'Computational Neuroscience', 3),
('APPM', 5380, 'Modeling in Applied Mathematics', 3),
('APPM', 5390, 'Modeling in Mathematical Biology', 3),
('APPM', 5430, 'Methods in Applied Mathematics: Applications of Complex Variables', 3),
('APPM', 5440, 'Applied Analysis 1', 3),
('APPM', 5450, 'Applied Analysis 2', 3),
('APPM', 5460, 'Methods in Applied Mathematics: Dynamical Systems and Differential Equations', 3),
('APPM', 5470, 'Methods of Applied Mathematics: Partial Differential and Integral Equations', 3),
('APPM', 5480, 'Methods of Applied Mathematics: Approximation Methods', 3),
('APPM', 5490, 'Theory of Machine Learning', 3),
('APPM', 5510, 'Data Assimilation in High Dimensional Dynamical Systems', 3),
('APPM', 5515, 'High-Dimensional Probability for Data Science', 3),
('APPM', 5530, 'Stochastic Analysis for Finance', 3),
('APPM', 5560, 'Markov Processes, Queues, and Monte Carlo Simulations', 3),
('APPM', 5565, 'Random Graphs', 3),
('APPM', 5570, 'Statistical Methods', 3),
('APPM', 5580, 'Introduction to Statistical Learning', 3),
('APPM', 5590, 'Statistical Modeling', 3),
('APPM', 5600, 'Numerical Analysis 1', 3),
('APPM', 5610, 'Numerical Analysis 2', 3),
('APPM', 5620, 'Numerical Linear Algebra', 3),
('APPM', 5650, 'Randomized Algorithms', 3),
('APPM', 6470, 'Advanced Partial Differential Equations', 3),
('APPM', 6520, 'Mathematical Statistics', 3),
('APPM', 6550, 'Introduction to Stochastic Processes', 3),
('APPM', 6560, 'Measure-Theoretic Probability', 3),
('APPM', 6570, 'Stochastic Differential Equations', 3),
('APPM', 6610, 'Introduction to Numerical Partial Differential Equations', 3),
('APPM', 6640, 'Multigrid Methods', 3),
('APPM', 7100, 'Mathematical Methods in Dynamical Systems', 3),
('APPM', 7300, 'Nonlinear Waves and Integrable Equations', 3),
('APPM', 8000, 'Colloquium in Applied Mathematics', 1),
('APPM', 8100, 'Seminar in Dynamical Systems', 1),
('APPM', 8400, 'Mathematical Biology Seminar', 1),
('APPM', 8500, 'Statistics, Optimization and Machine Learning Seminar', 1),
('APPM', 8600, 'Seminar in Computational Mathematics', 1),

('BCHM', 1020, 'A Path to Success: Introduction to the Biochemistry Major', 1),
('BCHM', 1041, 'Biotechnology and Society', 3),
('BCHM', 1701, 'Biochemistry Program for Research Exploration and Planning', 1),
('BCHM', 2700, 'Foundations of Biochemistry', 4),
('BCHM', 3100, 'Engineering RNA Aptamers', 2),
('BCHM', 3110, 'Literature-based Co-seminar for BCHM 3100 CURE Laboratory Course', 1),
('BCHM', 3491, 'Organic Chemistry 2 for Biochemistry Majors', 4),
('BCHM', 4312, 'Quantitative Optical Imaging', 3),
('BCHM', 4400, 'Core Concepts in Physical Chemistry for Biochemists', 4),
('BCHM', 4491, 'Modern Biophysical Methods', 3),
('BCHM', 4611, 'Principles of Biochemistry', 3),
('BCHM', 4621, 'Genome Databases: Mining and Management', 3),
('BCHM', 4631, 'Statistical and Computational Analysis of the Human Genome', 3),
('BCHM', 4720, 'Metabolic Pathways and Human Disease', 4),
('BCHM', 4740, 'Biochemistry of Gene Transmission, Expression and Regulation', 4),
('BCHM', 4751, 'Current Topics in Biochemical Research', 3),
('BCHM', 4761, 'Biochemistry Laboratory', 3),
('BCHM', 4850, 'Chemistry and Biology of Nucleic Acids', 3),
('BCHM', 5341, 'Chemical Biology and Drug Design', 3),
('BCHM', 5400, 'Core Concepts in Physical Chemistry for Biochemists', 4),
('BCHM', 5491, 'Modern Biophysical Methods', 3),
('BCHM', 5611, 'Principles of Biochemistry', 3),
('BCHM', 5621, 'Genome Databases: Mining and Management', 3),
('BCHM', 5631, 'Statistical and Computational Analysis of the Human Genome', 3),
('BCHM', 5661, 'Advances in Molecular Biophysics', 3),
('BCHM', 5720, 'Metabolic Pathways and Human Disease', 4),
('BCHM', 5740, 'Biochemistry of Gene Transmission, Expression and Regulation', 4),
('BCHM', 5751, 'Current Topics in Biochemical Research', 3),
('BCHM', 5770, 'Fundamentals of Biochemistry I', 3),
('BCHM', 5771, 'Advanced General Biochemistry 1', 5),
('BCHM', 5776, 'Scientific Ethics and Responsible Conduct in Research', 1),
('BCHM', 5780, 'Fundamentals of Biochemistry II', 3),
('BCHM', 5781, 'Advanced General Biochemistry 2', 5),
('BCHM', 5801, 'Advanced Signal Transduction and Cell Cycle Regulation', 3),
('BCHM', 5811, 'Advanced Methods in Protein Sequencing and Analysis', 3),
('BCHM', 5821, 'Special Topics in Signaling and Cell Regulation', 1),
('BCHM', 5850, 'Chemistry and Biology of Nucleic Acids', 3),
('BCHM', 6601, 'Biochemistry Seminar', 1),
('BCHM', 6941, 'Masters Candidate for Degree', 1),
('BCHM', 7601, 'Seminar: Nucleic Acid Chemistry', 3),
('BCHM', 7611, 'Seminar: Structures and Dynamics of Biopolymers in Solution', 1),
('BCHM', 7621, 'Seminar: Biochemistry and Molecular Biology of Signal Transduction', 1),
('BCHM', 7651, 'Seminar: Environmental Biochemistry', 2),
('BCHM', 7661, 'Structure/Function of Human Mediator Transcription Complexes', 1),
('BCHM', 7671, 'Seminar: Topics in Designing Probes for Signaling Reactions', 1),
('BCHM', 7691, 'Seminar: Protein Dynamics and the Mechanism of Sensory Proteins', 1),
('BCHM', 7701, 'Seminar: Enzyme Mechanisms and Kinetics', 1),
('BCHM', 7711, 'RNA Mediated Inorganic and Organic Reactions', 1),
('BCHM', 7741, 'Seminar: Signal Transduction and Protein Phosphorylation', 1),
('BCHM', 7751, 'Seminar: Protein Structure and Folding', 1),
('BCHM', 7761, 'Seminar: Eukaryotic Transcriptional Regulation', 1),
('BCHM', 7781, 'Seminar: Topics in Structural Biology', 1),
('BCHM', 7791, 'Seminar: Topics in Ribonucleoprotein Assemblies', 1),

('CHEN', 1201, 'General Chemistry for Engineers 1', 4),
('CHEN', 1203, 'General Chemistry for Engineers 2', 2),
('CHEN', 1211, 'Accelerated Chemistry for Engineers', 4),
('CHEN', 1300, 'Introduction to Chemical Engineering', 1),
('CHEN', 1310, 'Introduction to Engineering Computing', 3),
('CHEN', 1400, 'Drugs, Driving and Dynamic Processes', 3),
('CHEN', 2120, 'Chemical Engineering Material and Energy Balances', 3),
('CHEN', 2810, 'Biology for Engineers', 3),
('CHEN', 3010, 'Applied Data Analysis', 3),
('CHEN', 3200, 'Chemical Engineering Fluid Mechanics', 3),
('CHEN', 3210, 'Chemical Engineering Heat and Mass Transfer', 4),
('CHEN', 3211, 'Chemical Engineering Mass Transfer', 1),
('CHEN', 3220, 'Chemical Engineering Separations', 3),
('CHEN', 3320, 'Chemical Engineering Thermodynamics', 3),
('CHEN', 3660, 'Energy Fundamentals', 3),
('CHEN', 3930, 'Chemical Engineering Cooperative Education', 6),
('CHEN', 4010, 'Chemical Engineering Senior Thesis 1', 2),
('CHEN', 4020, 'Chemical Engineering Senior Thesis 2', 2),
('CHEN', 4090, 'Undergraduate Seminar', 1),
('CHEN', 4130, 'Chemical Engineering Laboratory', 3),
('CHEN', 4330, 'Chemical Engineering Reaction Kinetics', 3),
('CHEN', 4440, 'Chemical Engineering Materials', 3),
('CHEN', 4450, 'Polymer Chemistry', 3),
('CHEN', 4460, 'Polymer Engineering', 3),
('CHEN', 4480, 'Solar Cells and Optical Devices for Sustainable Buildings', 3),
('CHEN', 4490, 'Electrochemical Engineering', 3),
('CHEN', 4520, 'Chemical Process Synthesis', 3),
('CHEN', 4521, 'Physical Chemistry for Engineers', 3),
('CHEN', 4530, 'Chemical Engineering Design Project', 2),
('CHEN', 4570, 'Instrumentation and Process Control', 4),
('CHEN', 4630, 'Intellectual Property Law and Engineering', 1),
('CHEN', 4650, 'Particle Technology', 3),
('CHEN', 4801, 'Pharmaceutical Biotechnology', 3),
('CHEN', 4802, 'Tissue Engineering and Medical Devices', 3),
('CHEN', 4803, 'Metabolic Engineering', 3),
('CHEN', 4804, 'Protein and Enzyme Engineering', 3),
('CHEN', 4805, 'Biomaterials', 3),
('CHEN', 4810, 'Biological Engineering Laboratory', 3),
('CHEN', 4820, 'Biochemical Separations', 3),
('CHEN', 4830, 'Chemical Engineering Biokinetics', 3),
('CHEN', 4831, 'Biokinetics and Bioreactors Module', 1),
('CHEN', 4836, 'Nanomaterials', 3),
('CHEN', 5090, 'Seminar in Chemical Engineering', 1),
('CHEN', 5128, 'Applied Statistics In Research and Development', 3),
('CHEN', 5150, 'Biomolecular Kinetics, Transport, and Thermodynamics', 3),
('CHEN', 5160, 'Systems Analysis of Cells and Tissues', 3),
('CHEN', 5210, 'Transport Phenomena', 3),
('CHEN', 5360, 'Catalysis and Kinetics', 3),
('CHEN', 5370, 'Intermediate Chemical Engineering Thermodynamics', 3),
('CHEN', 5390, 'Chemical Reactor Engineering', 3),
('CHEN', 5420, 'Physical Chemistry and Fluid Mechanics of Interfaces', 3),
('CHEN', 5450, 'Polymer Chemistry', 3),
('CHEN', 5460, 'Polymer Engineering', 3),
('CHEN', 5470, 'Functional Materials Chemistry', 3),
('CHEN', 5480, 'Solar Cells and Optical Devices for Sustainable Buildings', 3),
('CHEN', 5490, 'Electrochemical Engineering', 3),
('CHEN', 5630, 'Intellectual Property Law and Engineering', 1),
('CHEN', 5650, 'Particle Technology', 3),
('CHEN', 5670, 'Environmental Separations', 3),
('CHEN', 5730, 'Mathematical Methods Short Course for Chemical Engineers', 1),
('CHEN', 5740, 'Analytical Methods in Chemical Engineering', 3),
('CHEN', 5750, 'Numerical Methods in Chemical Engineering', 3),
('CHEN', 5800, 'Bioprocess Engineering', 3),
('CHEN', 5803, 'Metabolic Engineering', 3),
('CHEN', 5804, 'Protein and Enzyme Engineering', 3),
('CHEN', 5805, 'Biological Interactions to Biomaterials', 3),
('CHEN', 5830, 'Introduction to Modern Biotechnology', 1),
('CHEN', 5831, 'Biotechnology Case Studies', 2),
('CHEN', 5835, 'Colloids and Interfaces', 3),
('CHEN', 5836, 'Nanomaterials', 3),
('CHEN', 5900, 'Pharmaceutical Biotechnology', 3),
('CHEN', 6210, 'Microhydrodynamics of Suspensions and Colloids', 3),

('CHEM', 1011, 'Environmental Chemistry 1', 3),
('CHEM', 1021, 'Introductory Chemistry', 4),
('CHEM', 1031, 'Environmental Chemistry 2', 4),
('CHEM', 1113, 'General Chemistry 1', 4),
('CHEM', 1114, 'Laboratory in General Chemistry 1', 1),
('CHEM', 1133, 'General Chemistry 2', 4),
('CHEM', 1134, 'Laboratory in General Chemistry 2', 1),
('CHEM', 1221, 'Engineering General Chemistry Lab', 1),
('CHEM', 1400, 'Foundations of Chemistry', 4),
('CHEM', 1401, 'Foundations of Chemistry Lab', 1),
('CHEM', 2100, 'Foundations of Chemistry 2', 4),
('CHEM', 2101, 'Laboratory in Foundations of Chemistry 2', 4),
('CHEM', 3151, 'Air Chemistry and Pollution', 3),
('CHEM', 3251, 'Sustainable Energy from a Chemistry Perspective', 3),
('CHEM', 3311, 'Organic Chemistry 1', 4),
('CHEM', 3321, 'Laboratory in Organic Chemistry 1', 1),
('CHEM', 3331, 'Organic Chemistry 2', 4),
('CHEM', 3341, 'Laboratory in Organic Chemistry 2', 1),
('CHEM', 3361, 'Laboratory in Organic Chemistry 1 for Chemistry Majors', 2),
('CHEM', 3381, 'Laboratory in Organic Chemistry 2 for Chemistry Majors', 2),
('CHEM', 3451, 'Organic Chemistry 1 for Chemistry and Biochemistry Majors', 4),
('CHEM', 3471, 'Organic Chemistry 2 for Chemistry Majors', 4),
('CHEM', 4011, 'Modern Inorganic Chemistry', 3),
('CHEM', 4021, 'Inorganic Laboratory', 3),
('CHEM', 4141, 'Environmental Water and Soil Chemistry', 3),
('CHEM', 4171, 'Instrumental Analysis - Lecture and Laboratory 1', 3),
('CHEM', 4181, 'Instrumental Analysis - Lecture and Laboratory 2', 3),
('CHEM', 4251, 'Materials Chemistry and Properties', 3),
('CHEM', 4261, 'Organic Materials: Structures and Functions', 3),
('CHEM', 4271, 'Chemistry of Solar Energy', 3),
('CHEM', 4511, 'Physical Chemistry 1', 3),
('CHEM', 4531, 'Physical Chemistry 2', 3),
('CHEM', 4555, 'Theoretical and Computational Chemistry', 4),
('CHEM', 4581, 'Physical Chemistry Lab 1', 1),
('CHEM', 4591, 'Physical Chemistry Lab 2', 2),
('CHEM', 5011, 'Advanced Inorganic Chemistry 1', 3),
('CHEM', 5061, 'Advanced Inorganic Chemistry 2', 3),
('CHEM', 5131, 'Computer Programming and Data Analysis for Chemists', 3),
('CHEM', 5141, 'Environmental Water and Soil Chemistry', 3),
('CHEM', 5151, 'Atmospheric Chemistry', 3),
('CHEM', 5152, 'Advanced Atmospheric Chemistry', 3),
('CHEM', 5161, 'Analytical Atmospheric Spectroscopy', 3),
('CHEM', 5171, 'Electroanalytical Chemistry', 3),
('CHEM', 5181, 'Mass Spectrometry, Chromatography, and Computer Programming', 3),
('CHEM', 5251, 'Materials Chemistry and Properties', 3),
('CHEM', 5261, 'Organic Materials: Structures and Functions', 3),
('CHEM', 5271, 'Chemistry of Solar Energy', 3),
('CHEM', 5281, 'Semiconductor Processing and Device Fabrication', 3),
('CHEM', 5311, 'Advanced Synthetic Organic Chemistry', 3),
('CHEM', 5321, 'Advanced Physical Organic Chemistry', 3),
('CHEM', 5331, 'Advanced Spectroscopic Techniques in Organic Chemistry', 3),
('CHEM', 5501, 'Advanced Topics in Physical Chemistry', 3),
('CHEM', 5531, 'Statistical Mechanics', 3),
('CHEM', 5541, 'Chemical Dynamics', 3),
('CHEM', 5555, 'Theoretical and Computational Chemistry', 4),
('CHEM', 5571, 'Surface Science', 3),
('CHEM', 5581, 'Introductory Quantum Chemistry', 3),
('CHEM', 5591, 'Advanced Molecular Spectroscopy', 3),
('CHEM', 6001, 'Seminar: Inorganic Chemistry', 1),
('CHEM', 6031, 'Special Topics in Nanoscience', 3),
('CHEM', 6101, 'Seminar: Analytical Chemistry', 1),
('CHEM', 6941, 'Masters Candidate for Degree', 3),
('CHEM', 7021, 'Seminar: Structural Inorganic Chemistry', 2),
('CHEM', 7101, 'Seminar: Chromatography and Trace Analysis', 2),
('CHEM', 7111, 'Seminar: Electrochemistry', 2),
('CHEM', 7131, 'Seminar in Atmospheric Aerosol Chemistry', 3),
('CHEM', 7161, 'Seminar: Heterogeneous Atmospheric Chemistry', 1),
('CHEM', 7211, 'Seminar: Topics in Synthetic Methodology and Natural Product Synthesis', 1),
('CHEM', 7221, 'Seminar: Photochemistry and Free Radical Chemistry', 1),
('CHEM', 7231, 'Seminar: Reactive Intermediates', 1),
('CHEM', 7241, 'Seminar: Synthetic Organic Chemistry', 1),
('CHEM', 7251, 'Selected Topics in Chemical Genetics', 1),
('CHEM', 7271, 'Seminar: Picosecond Dynamics of Reactions', 1),
('CHEM', 7281, 'Seminar: Molecular Self-Assembly', 1),
('CHEM', 7291, 'Seminar: Physical Organic Chemistry', 1),
('CHEM', 7301, 'Seminar: Synthetic and Mechanistic Chemistry', 1),

('CVEN', 1027, 'Civil Engineering Drawing', 3),
('CVEN', 1317, 'Introduction to Civil and Environmental Engineering', 1),
('CVEN', 2012, 'Introduction to Geomatics', 3),
('CVEN', 2017, 'Excel Matlab R Primer', 1),
('CVEN', 2121, 'Analytical Mechanics 1', 3),
('CVEN', 3022, 'Construction Surveying', 3),
('CVEN', 3032, 'Photogrammetry', 3),
('CVEN', 3111, 'Analytical Mechanics 2', 3),
('CVEN', 3141, 'Engineering Materials Lab', 2),
('CVEN', 3161, 'Mechanics of Materials 1', 3),
('CVEN', 3227, 'Probability, Statistics and Decision', 3),
('CVEN', 3246, 'Introduction to Construction', 3),
('CVEN', 3256, 'Construction Equipment and Methods', 3),
('CVEN', 3313, 'Theoretical Fluid Mechanics', 3),
('CVEN', 3323, 'Hydraulic Engineering', 3),
('CVEN', 3414, 'Fundamentals of Environmental Engineering', 3),
('CVEN', 3424, 'Water and Wastewater Treatment', 3),
('CVEN', 3434, 'Introduction to Applied Ecology', 3),
('CVEN', 3525, 'Structural Analysis', 3),
('CVEN', 3602, 'Transportation Systems', 3),
('CVEN', 3698, 'Engineering Geology', 3),
('CVEN', 3708, 'Geotechnical Engineering 1', 3),
('CVEN', 3718, 'Geotechnical Engineering 2', 3),
('CVEN', 4147, 'Civil Engineering Systems', 3),
('CVEN', 4157, 'A Systems Approach to Global Engineering', 3),
('CVEN', 4161, 'Mechanics of Materials 2', 3),
('CVEN', 4323, 'Water Resources Engineering Design', 3),
('CVEN', 4333, 'Engineering Hydrology', 3),
('CVEN', 4353, 'Groundwater Engineering', 3),
('CVEN', 4383, 'Applied Groundwater Modeling', 3),
('CVEN', 4404, 'Water Chemistry', 3),
('CVEN', 4414, 'Water Chemistry Laboratory', 1),
('CVEN', 4424, 'Environmental Organic Chemistry', 3),
('CVEN', 4434, 'Environmental Engineering Design', 4),
('CVEN', 4464, 'Environmental Engineering Processes', 3),
('CVEN', 4474, 'Hazardous and Industrial Waste Management', 3),
('CVEN', 4484, 'Introduction to Environmental Microbiology', 3),
('CVEN', 4511, 'Introduction to Finite Element Analysis', 3),
('CVEN', 4525, 'Matrix Structural Analysis', 3),
('CVEN', 4537, 'Numerical Methods in Civil Engineering', 3),
('CVEN', 4545, 'Steel Design', 3),
('CVEN', 4554, 'Fundamentals of Air Quality Management', 3),
('CVEN', 4555, 'Reinforced Concrete Design', 3),
('CVEN', 4565, 'Design of Wood Structures', 3),
('CVEN', 4594, 'Water Reuse and Reclamation', 3),
('CVEN', 4718, 'Mechanics and Dynamics of Glaciers', 3),
('CVEN', 4728, 'Foundation Engineering', 3),
('CVEN', 4897, 'Professional Issues in Civil Engineering', 2),
('CVEN', 4899, 'Civil Engineering Senior Project Design', 4),
('CVEN', 4969, 'Water and Sanitation in Developing Countries', 3),
('CVEN', 5006, 'Construction Engineering and Management Fundamentals', 3),
('CVEN', 5111, 'Structural Dynamics', 3),
('CVEN', 5131, 'Continuum Mechanics and Elasticity', 3),
('CVEN', 5147, 'Civil Engineering Systems', 3),
('CVEN', 5151, 'Wave Methods for Design and Characterization of Advanced Materials', 3),
('CVEN', 5157, 'A Systems Approach to Global Engineering', 3),
('CVEN', 5161, 'Advanced Mechanics of Materials I', 3),
('CVEN', 5206, 'Design Development', 3),
('CVEN', 5226, 'Construction Safety', 3),
('CVEN', 5246, 'Legal Aspects of Construction', 3),
('CVEN', 5276, 'Engineering Risk and Decision Analysis', 3),
('CVEN', 5286, 'Design Construction Operations', 3),
('CVEN', 5313, 'Environmental Fluid Mechanics', 3),
('CVEN', 5323, 'Applied Stream Ecology', 3),
('CVEN', 5333, 'Physical Hydrology', 3),
('CVEN', 5343, 'Transport and Dispersion in Surface Water', 3),
('CVEN', 5346, 'Managing Construction and Engineering Projects and Organizations', 3),
('CVEN', 5353, 'Groundwater Hydrology', 3),
('CVEN', 5363, 'Modeling of Hydrologic Systems', 3),
('CVEN', 5373, 'Water Law, Policy, and Institutions', 3),
('CVEN', 5383, 'Applied Groundwater Modeling', 3),
('CVEN', 5393, 'Water Resources System and Management', 3),
('CVEN', 5404, 'Water Chemistry', 3),
('CVEN', 5414, 'Water Chemistry Laboratory', 3),
('CVEN', 5423, 'Water Resources Engineering Design', 3),
('CVEN', 5424, 'Environmental Organic Chemistry', 3),
('CVEN', 5434, 'Environmental Engineering Design', 3),
('CVEN', 5444, 'Municipal Des Proj', 3),
('CVEN', 5454, 'Statistical Methods for Natural and Engineered Systems', 3),
('CVEN', 5464, 'Environmental Engineering Processes', 3),
('CVEN', 5474, 'Hazardous and Industrial Waste Management', 3),
('CVEN', 5484, 'Applied Microbiology and Toxicology', 3),
('CVEN', 5494, 'Surface Water Quality Modeling', 3),
('CVEN', 5511, 'Introduction to Finite Element Analysis', 3),
('CVEN', 5514, 'Bioremediation', 3),
('CVEN', 5524, 'Drinking Water Treatment', 3),
('CVEN', 5525, 'Matrix Structural Analysis', 3),
('CVEN', 5534, 'Wastewater Treatment', 3),
('CVEN', 5537, 'Numerical Methods in Civil Engineering', 3),
('CVEN', 5544, 'Solid Waste Management and Resource Recovery', 3),
('CVEN', 5554, 'Fundamentals of Air Quality Management', 3),
('CVEN', 5564, 'Water Profession: Communication and Utility Finance', 3),
('CVEN', 5565, 'Life-Cycle Engineering of Civil Infrastructure Systems', 3),
('CVEN', 5574, 'Water Utility Management: Current Issues and Future Challenges', 3),
('CVEN', 5575, 'Advanced Topics in Steel Design', 3),
('CVEN', 5584, 'Water Profession: Leadership and Management', 3),
('CVEN', 5585, 'Advanced Topics in Reinforced Concrete Design', 3),
('CVEN', 5594, 'Water Reuse and Reclamation', 3),
('CVEN', 5604, 'UV Disinfection and Advanced Oxidation', 3),
('CVEN', 5614, 'Bioenergy & Bioresource Recovery', 3),
('CVEN', 5628, 'Seepage and Slopes', 3),
('CVEN', 5678, 'Soil Improvement and Reinforcement', 3),
('CVEN', 5688, 'Environmental Geotechnics', 3),
('CVEN', 5708, 'Soil Mechanics', 3),
('CVEN', 5718, 'Mechanics and Dynamics of Glaciers', 3),
('CVEN', 5728, 'Foundation Engineering', 3),
('CVEN', 5738, 'Applied Geotechnical Analysis', 3),
('CVEN', 5748, 'Design of Earth Structures', 3),
('CVEN', 5758, 'Flow Processes in Soils', 3),
('CVEN', 5768, 'Introduction to Rock Mechanics', 3),
('CVEN', 5788, 'Computational Modeling in Geotechnical Engineering', 3),
('CVEN', 5798, 'Dynamics of Soils and Structures', 3),
('CVEN', 5818, 'Geotechnical Earthquake Engineering', 3),
('CVEN', 5822, 'Geographical Information Systems for Civil and Environmental Systems', 3),
('CVEN', 5831, 'Special Topics', 3),
('CVEN', 5899, 'Graduate Engineering Internship Experience', 1),
('CVEN', 5919, 'Global Development for Engineers', 3),
('CVEN', 5929, 'Sustainable Community Development 2', 3),
('CVEN', 5939, 'Global Development Practicum', 3),
('CVEN', 6161, 'Advanced Mechanics of Materials 2', 3),
('CVEN', 6333, 'Introduction to Multi-Scale Variability and Scaling in Hydrology', 3),
('CVEN', 6383, 'Flow and Transport through Porous Media', 3),
('CVEN', 6393, 'Hydrologic Sciences and Water Resources Engineering Seminar', 3),
('CVEN', 6414, 'Aquatic Surfaces and Particles', 3),
('CVEN', 6511, 'Nonlinear Finite Element Analysis of Solids and Porous Media', 3),
('CVEN', 6525, 'Nonlinear Analysis of Framed Structures', 3),
('CVEN', 6595, 'Earthquake Engineering', 3),
('CVEN', 6937, 'Sp Tpcs Comp Graphics', 3),
('CVEN', 7111, 'Advanced Structural Dynamics', 3),
('CVEN', 7141, 'Plates and Shells', 3),
('CVEN', 7161, 'Fracture Mechanics', 3),
('CVEN', 7511, 'Computational Finite Inelasticity and Multiphase Mechanics', 3),
('CVEN', 7718, 'Engineering Properties of Soils', 3),
('CVEN', 7788, 'Soil Behavior', 3),

('COEN', 1400, 'Project Design', 3),
('COEN', 1500, 'CEAS Design Lab: Engineering Your Life', 1),
('COEN', 1510, 'Self Management and Leadership Principles 1', 1),
('COEN', 1520, 'Self Management and Leadership Principles 2', 1),
('COEN', 1550, 'YOURE@CU: Undergraduate Career Seminar', 1),
('COEN', 1830, 'Special Topics: Engineering First-Year Symposium', 1),
('COEN', 2880, 'Fresh Start for Success', 1),
('COEN', 3051, 'Leadership Seminar 1: Launching the Leadership Experience', 2),
('COEN', 3052, 'Leadership Seminar 2: Leadership Experience', 2),
('COEN', 5053, 'Leadership Seminar 3: ELP Synthesis and Final ePortfolio', 2),
('COEN', 3100, 'Engineering Transfer Student Success Seminar', 1),
('COEN', 3210, 'Climate Change and Engineering', 3),

('ECEN', 1100, 'Exploring ECE', 1),
('ECEN', 1310, 'C Programming for ECE', 4),
('ECEN', 1400, 'Introduction to Digital and Analog Electronics', 3),
('ECEN', 1500, 'Sustainable Energy', 3),
('ECEN', 2250, 'Introduction to Circuits and Electronics', 3),
('ECEN', 2260, 'Circuits as Systems', 3),
('ECEN', 2270, 'Electronics Design Lab', 3),
('ECEN', 2350, 'Digital Logic', 4),
('ECEN', 2360, 'Programming Digital Systems', 3),
('ECEN', 2370, 'Embedded Software Engineering', 3),
('ECEN', 2410, 'Renewable Sources and Efficient Electrical Energy Systems', 3),
('ECEN', 2420, 'Electronics for Wireless Systems', 3),
('ECEN', 2400, 'Application of Embedded Systems', 3),
('ECEN', 2450, 'Electronic and Semiconductor Device Laboratory', 3),
('ECEN', 2703, 'Discrete Mathematics for Computer Engineers', 3),
('ECEN', 3010, 'Circuits and Electronics for Mechanical Engineers', 3),
('ECEN', 3090, 'Electro', 3),
('ECEN', 3170, 'Electromagnetic Energy Conversion 1', 3),
('ECEN', 3210, 'Hype and Reality in Energy Technologies', 3),
('ECEN', 3250, 'Microelectronics', 3),
('ECEN', 3300, 'Linear Systems', 3),
('ECEN', 3301, 'Biomedical Signals and Systems', 3),
('ECEN', 3303, 'Introduction to Robotics', 3),
('ECEN', 3320, 'Semiconductor Devices', 3),
('ECEN', 3350, 'Programming Digital Systems', 3),
('ECEN', 3400, 'Electromagnetic Fields and Waves', 3),
('ECEN', 3410, 'Electromagnetic Waves and Transmission', 3),
('ECEN', 3593, 'Computer Organization', 3),
('ECEN', 3753, 'Real-Time Operating Systems', 3),
('ECEN', 3763, 'FPGA Design and HDL', 3),
('ECEN', 3810, 'Introduction to Probability Theory', 3),
('ECEN', 4111, 'Engineering Applications in Biomedicine: Cardiovascular Devices and Systems', 3),
('ECEN', 4121, 'Design of Implantable Medical Devices: Neuromodulation', 3),
('ECEN', 4133, 'Fundamentals of Computer Security', 3),
('ECEN', 4138, 'Control Systems Analysis', 3),
('ECEN', 4167, 'Electromagnetic Energy Conversion 2', 3),
('ECEN', 4224, 'High Speed Digital Design', 3),
('ECEN', 4242, 'Communication Theory', 3),
('ECEN', 4213, 'Concurrent Programming', 3),
('ECEN', 4322, 'Data and Network Science', 3),
('ECEN', 4341, 'Bioelectromagnetics', 3),
('ECEN', 4395, 'Organic Electronic Materials and Devices', 3),
('ECEN', 4423, 'Chaotic Dynamics', 3),
('ECEN', 4517, 'Power Electronics and Photovoltaic Power Systems Laboratory', 3),
('ECEN', 4532, 'Digital Signal Processing Laboratory', 3),
('ECEN', 4553, 'Compiler Construction', 3),
('ECEN', 4555, 'Principles of Energy Systems and Devices', 3),
('ECEN', 4583, 'Software System Development', 3),
('ECEN', 4606, 'Undergraduate Optics Laboratory', 3),
('ECEN', 4610, 'Capstone Laboratory Part 1', 3),
('ECEN', 4616, 'Optoelectronic System Design', 3),
('ECEN', 4620, 'Capstone Lab, Part 2', 3),
('ECEN', 4632, 'Introduction to Digital Filtering', 3),
('ECEN', 4634, 'Microwave and RF Laboratory', 3),
('ECEN', 4638, 'Control Systems Laboratory', 3),
('ECEN', 4693, 'Advanced Computer Architecture', 3),
('ECEN', 4720, 'Practical Printed Circuit Board Design Accelerator', 1),
('ECEN', 4730, 'Practical Printed Circuit Board Design and Manufacture', 3),
('ECEN', 4752, 'Communication Laboratory', 3),
('ECEN', 4753, 'Computer Performance Modeling', 3),
('ECEN', 4763, 'Embedded Software Algorithms', 3),
('ECEN', 4797, 'Introduction to Power Electronics', 3),
('ECEN', 4827, 'Analog IC Design', 3),
('ECEN', 4915, 'Foundations of Quantum Engineering', 3),
('ECEN', 4933, 'Engineering Genetic Circuits', 3),
('ECEN', 5100, 'Graduate Seminar and Professional Development', 1),
('ECEN', 5104, 'Passive Microwave Circuits', 3),
('ECEN', 5107, 'Electric Power Grid', 3),
('ECEN', 5111, 'Engineering Applications in Biomedicine: Cardiovascular Devices and Systems', 3),
('ECEN', 5114, 'Electromagnetic Theory', 3),
('ECEN', 5121, 'Design of Implantable Medical Devices: Neuromodulation', 3),
('ECEN', 5122, 'Wireless Local Area Networks', 3),
('ECEN', 5126, 'Computational Optical Imaging', 3),
('ECEN', 5133, 'Fundamentals of Computer Security', 3),
('ECEN', 5134, 'Electromagnetic Radiation and Antennas', 3),
('ECEN', 5138, 'Control Systems Analysis', 3),
('ECEN', 5139, 'Computer-Aided Verification', 3),
('ECEN', 5154, 'Computational Electromagnetics', 3),
('ECEN', 5156, 'Physical Optics', 3),
('ECEN', 5164, 'Electromagnetic Metamaterials', 3),
('ECEN', 5224, 'High Speed Digital Design', 3),
('ECEN', 5244, 'Stochastic / Environmental Signal Processing', 3),
('ECEN', 5254, 'Remote Sensing Signals and Systems', 3),
('ECEN', 5264, 'Electromagnetic Absorption, Scattering, and Propagation', 3),
('ECEN', 5273, 'Network Systems', 3),
('ECEN', 5313, 'Concurrent Programming', 3),
('ECEN', 5322, 'Data and Network Science', 3),
('ECEN', 5341, 'Bioelectromagnetics', 3),
('ECEN', 5345, 'Introduction to Solid State Physics', 3),
('ECEN', 5355, 'Principles of Electronic Devices 1', 3),
('ECEN', 5358, 'Optimization and Optimal Control', 3),
('ECEN', 5395, 'Organic Electronic Materials and Devices', 3),
('ECEN', 5407, 'Renewable Energy and the Future Power Grid', 3),
('ECEN', 5414, 'Essential Principles of Signal Integrity', 3),
('ECEN', 5417, 'Power System Analysis', 3),
('ECEN', 5423, 'Chaotic Dynamics', 3),
('ECEN', 5427, 'Power System Planning & Operations', 3),
('ECEN', 5437, 'Distribution System Analysis', 3),
('ECEN', 5447, 'Power System Dynamics with Renewable Energy', 3),
('ECEN', 5448, 'Advanced Linear Systems', 3),
('ECEN', 5457, 'Energy Systems Optimization', 3),
('ECEN', 5458, 'Sampled Data and Digital Control Systems', 3),
('ECEN', 5467, 'Data Analytics and Data-Driven Decision Making for Modern Power and Energy Systems', 3),
('ECEN', 5478, 'Online Convex Optimization and Learning', 3),
('ECEN', 5488, 'Geometric Control Theory', 3),
('ECEN', 5498, 'Stochastic Control Theory', 3),
('ECEN', 5514, 'Principles of Electromagnetics for High-Speed Digital Engineering', 3),
('ECEN', 5517, 'Power Electronics and Photovoltaic Power Systems Laboratory', 3),
('ECEN', 5523, 'Compiler Construction', 3),
('ECEN', 5524, 'Principles of Computational Electromagnetics for Signal and Power Integrity', 3),
('ECEN', 5527, 'Power Electronics Power Lab', 3),
('ECEN', 5532, 'Digital Signal Processing Laboratory', 3),
('ECEN', 5533, 'Fundamental Concepts of Programming Languages', 3),
('ECEN', 5543, 'Software Engineering of Standalone Programs', 3),
('ECEN', 5544, 'EM Signal Modeling for HSDE using Ansys HFSS and Q3D', 3),
('ECEN', 5555, 'Principles of Energy Systems and Devices', 3),
('ECEN', 5565, 'Advanced Network Systems', 3),
('ECEN', 5573, 'Advanced Operating Systems', 3),
('ECEN', 5592, 'Modern Signal Processing', 3),
('ECEN', 5593, 'Advanced Computer Architecture', 3),
('ECEN', 5603, 'Software Project Management', 3),
('ECEN', 5606, 'Optics Laboratory', 3),
('ECEN', 5607, 'Power Electronics for Electrified Transportation', 3),
('ECEN', 5612, 'Random Processes for Engineers', 3),
('ECEN', 5613, 'Embedded System Design', 3),
('ECEN', 5616, 'Optoelectric System Design', 3),
('ECEN', 5622, 'Information Theory and Coding', 3),
('ECEN', 5623, 'Real-Time Embedded Systems', 3),
('ECEN', 5626, 'Active Optical Devices', 3),
('ECEN', 5632, 'Theory and Application of Digital Filtering', 3),
('ECEN', 5634, 'Microwave and RF Laboratory', 3),
('ECEN', 5638, 'Control Systems Laboratory', 3),
('ECEN', 5645, 'Introduction to Optical Electronics', 3),
('ECEN', 5652, 'Detection and Extraction of Signals from Noise', 3),
('ECEN', 5672, 'Digital Image Processing', 3),
('ECEN', 5673, 'Distributed Systems', 3),
('ECEN', 5678, 'Control of Multi-agent Systems', 3),
('ECEN', 5682, 'Theory and Practice of Error Control Codes', 3),
('ECEN', 5692, 'Principles of Digital Communication', 3),
('ECEN', 5696, 'Fourier Optics', 3),
('ECEN', 5713, 'Advanced Embedded Software Development', 3),
('ECEN', 5720, 'Practical Printed Circuit Board Design Accelerator', 1),
('ECEN', 5730, 'Practical Printed Circuit Board Design and Manufacture', 3),
('ECEN', 5737, 'Adjustable-Speed AC Drives', 3),
('ECEN', 5738, 'Theory of Nonlinear Systems', 3),
('ECEN', 5752, 'Communication Laboratory', 3),
('ECEN', 5753, 'Computer Performance Modeling', 3),
('ECEN', 5763, 'Embedded Machine Vision and Intelligent Automation', 3),
('ECEN', 5773, 'Developing the Industrial Internet of Things', 3),
('ECEN', 5783, 'Embedded Interface Design', 3),
('ECEN', 5793, 'Secure Computer Architecture', 3),
('ECEN', 5797, 'Introduction to Power Electronics', 3),
('ECEN', 5803, 'Mastering Embedded Systems Architecture', 3),
('ECEN', 5807, 'Modeling and Control of Power Electronic Systems', 3),
('ECEN', 5813, 'Principles of Embedded Software', 3),
('ECEN', 5817, 'Resonant and Soft-Switching Techniques in Power Electronics', 3),
('ECEN', 5821, 'Neural Systems and Physiological Control', 3),
('ECEN', 5823, 'Internet of Things Embedded Firmware', 3),
('ECEN', 5827, 'Analog IC Design', 3),
('ECEN', 5828, 'Hybrid Dynamical Systems: Theory and Applications', 3),
('ECEN', 5833, 'Low Power Embedded Design Techniques', 3),
('ECEN', 5837, 'Mixed-Signal IC Design Lab', 3),
('ECEN', 5853, 'Embedding Sensors and Motors', 3),
('ECEN', 5857, 'Digital Control for Power Electronics', 3),
('ECEN', 5863, 'Programmable Logic Embedded System Design', 3),
('ECEN', 5915, 'Foundations of Quantum Engineering', 3),
('ECEN', 5933, 'Engineering Genetic Circuits', 3),
('ECEN', 6139, 'Logic Synthesis of VLSI Systems', 3),
('ECEN', 6144, 'Electromagnetic Boundary Problems', 3),

('ENEN', 4321, 'Oil and Gas Processing', 3),
('ENEN', 4600, 'Interdisciplinary Energy Engineering Projects', 3),

('ENES', 1010, 'Engineering, Ethics and Society', 3),
('ENES', 1843, 'Special Topics', 3),
('ENES', 1850, 'Engineering in History: The Social Impact of Technology', 3),
('ENES', 2010, 'Tradition and Identity', 3),
('ENES', 2020, 'The Meaning of Information Technology', 3),
('ENES', 2100, 'History of Science and Technology to Newton', 3),
('ENES', 2120, 'History of Modern Science from Newton to Einstein', 3),
('ENES', 2130, 'History of Modern Technology from 1750 to the Atomic Bomb', 3),
('ENES', 2210, 'Modern Science and Technological Society', 3),
('ENES', 2346, 'Women and Engineering', 3),
('ENES', 2360, 'Gaining a Global State of Mind for Effective Engineering Practice', 3),
('ENES', 2840, 'Lower Division: Independent Study', 3),
('ENES', 3100, 'Seminar in Engineering, Ethics & Society', 3),
('ENES', 3200, 'Humanities for Engineers 2', 3),
('ENES', 3210, 'Modern Science and the Technological Society', 3),
('ENES', 3280, 'Science and Religion', 3),
('ENES', 3320, 'Don Quixotes Spain', 3),
('ENES', 3330, 'Science Fiction and Philosophy', 3),
('ENES', 3340, 'Leonardo da Vincis World', 3),
('ENES', 3346, 'Women and Engineering', 3),
('ENES', 3350, 'Gods, Heroes and Engineers: The Western Quest for Excellence', 3),
('ENES', 3360, 'Gaining a Global State of Mind for Effective Engineering Practice', 3),
('ENES', 3370, 'Harry Potter and the Conflict of Being', 3),
('ENES', 3430, 'Ethics of Genetic Engineering: A Multidisciplinary Approach', 3),
('ENES', 3450, 'Narrative Medicine', 3),
('ENES', 3543, 'History of Western Medicine', 3),
('ENES', 3700, 'Culture Wars in Rome', 3),
('ENES', 3720, 'Voices of Vienna: Freud, Wittgenstien, Mozart', 3),
('ENES', 3750, 'Xian, China: Self-Awareness and Images of the Other', 3),
('ENES', 3858, 'American Comics and Graphic Novels', 3),
('ENES', 4200, 'Humanities for Engineers 4', 3),
('ENES', 4800, 'Leadership & Ethics in the Real World', 1),

('EDEN', 4147, 'A Systems Approach to Global Engineering', 3),
('EDEN', 5147, 'A Systems Approach to Global Engineering', 3),

('EHON', 1500, 'Honors Reading Group', 1),
('EHON', 3843, 'Special Topics', 3),
('EHON', 4051, 'Dimensions of Leadership', 1),
('EHON', 4151, 'Critical Encounters 2', 3),

('EMEN', 3100, 'Introduction to Engineering Management', 3),
('EMEN', 4030, 'Project Management Systems', 3),
('EMEN', 4050, 'Leadership and Professional Skills', 3),
('EMEN', 4055, 'Designing for Diversity, Equity and Inclusion in Engineering', 3),
('EMEN', 4100, 'Engineering Economics', 3),
('EMEN', 4110, 'Supply Chain Management', 3),
('EMEN', 4120, 'Managing Business Processes', 3),
('EMEN', 4200, 'Engineering and Entrepreneurship for the Developing World', 3),
('EMEN', 4400, 'Quality Management', 3),
('EMEN', 4405, 'Systems Engineering', 3),
('EMEN', 4800, 'Technology Ventures and Marketing', 3),
('EMEN', 4820, 'Entrepreneurial Product Development', 3),
('EMEN', 4825, 'New Venture Creation', 3),
('EMEN', 4850, 'Entrepreneurial Leadership', 3),
('EMEN', 4875, 'Entrepreneurial Finance', 3),
('EMEN', 5000, 'Engineering Principles', 3),
('EMEN', 5005, 'Introduction to Applied Statistical Methods', 3),
('EMEN', 5010, 'Introduction to Engineering Management', 3),
('EMEN', 5015, 'Engineering Communication', 3),
('EMEN', 5020, 'Finance for Engineering Managers', 3),
('EMEN', 5030, 'Fundamentals of Project Management', 3),
('EMEN', 5031, 'Software Project Management', 3),
('EMEN', 5032, 'Project Management Application and Execution', 3),
('EMEN', 5041, 'Performance Excellence for Business and Service', 3),
('EMEN', 5042, 'Data Science for Quality Improvement', 3),
('EMEN', 5043, 'Systems for Quality Improvement', 3),
('EMEN', 5050, 'Leading Oneself', 3),
('EMEN', 5052, 'Leading Others', 3),
('EMEN', 5053, 'Leading Technical Organizations', 3),
('EMEN', 5054, 'Neuroscience of Leadership', 3),
('EMEN', 5055, 'Leading for Diversity, Equity and Inclusion in Engineering', 3),
('EMEN', 5065, 'Global Topics in Aerospace', 3),
('EMEN', 5080, 'Ethical Decision-Making in Engineering Management', 3),
('EMEN', 5090, 'Marketing and Technology Ventures', 3),
('EMEN', 5094, 'Entrepreneurship for Engineers', 3),
('EMEN', 5215, 'Principles & Practices of the Sustainable Enterprise', 3),
('EMEN', 5315, 'Business Law for Engineering Managers', 3),
('EMEN', 5316, 'Engineering, Product Liability & The Litigation Process', 3),
('EMEN', 5400, 'Product Development and Design', 3),
('EMEN', 5405, 'Fundamentals of Systems Engineering', 3),
('EMEN', 5500, 'Lean and Agile Management', 3),
('EMEN', 5610, 'Advanced Statistical Methods for Engineering Research', 3),
('EMEN', 5620, 'Data Mining and Screening Experiments for Engineering Research', 3),
('EMEN', 5710, 'Enterprise Strategic Management', 3),
('EMEN', 5825, 'Intrapreneurship & Innovation', 3),
('EMEN', 5900, 'Research Methods and Experimental Design', 3),

('GEEN', 1010, 'Engineering Explorations Through Physics', 4),
('GEEN', 1017, 'Engineering Drawing', 3),
('GEEN', 1400, 'Engineering Projects', 3),
('GEEN', 2010, 'Engineering Tools and Analysis', 3),
('GEEN', 2400, 'Engineering Projects for the Community', 3),
('GEEN', 2851, 'Statics for Engineers', 3),
('GEEN', 3010, 'Circuits for Engineers', 3),
('GEEN', 3024, 'Materials Science for Engineers', 3),
('GEEN', 3400, 'Invention and Innovation', 3),
('GEEN', 3852, 'Thermodynamics for Engineers', 3),
('GEEN', 3853, 'Data Analysis for Engineers', 4),
('GEEN', 4400, 'Teaching Design', 3),

('EVEN', 1000, 'Introduction to Environmental Engineering', 1),
('EVEN', 1001, 'Environmental Engineering 101: An Introduction to Pollution Science', 3),
('EVEN', 2909, 'Introduction to Global Engineering', 3),
('EVEN', 3012, 'Environmental Engineering Thermodynamics', 3),
('EVEN', 3550, 'Sustainability Principles for Engineers', 3),
('EVEN', 3650, 'Sustainable Energy Systems Analysis', 3),
('EVEN', 4100, 'Environmental Sampling and Analysis', 3),
('EVEN', 4404, 'Water Chemistry', 3),
('EVEN', 4414, 'Water Chemistry Laboratory', 1),
('EVEN', 4424, 'Environmental Organic Chemistry', 3),
('EVEN', 4434, 'Environmental Engineering Design', 4),
('EVEN', 4464, 'Environmental Engineering Processes', 3),
('EVEN', 4484, 'Introduction to Environmental Microbiology', 3),
('EVEN', 4494, 'Contaminant Fate and Transport', 3),
('EVEN', 4969, 'Water and Sanitation in Developing Countries', 3),
('EVEN', 5444, 'Analytical Methods, Experimental Design, and Applied Data Analysis', 3),
('EVEN', 5584, 'Sustainable Engineering Design', 3),
('EVEN', 6504, 'Advanced Physical-Chemical Processes for Water and Water Reuse Treatment', 3),

('MSEN', 5064, 'Soft Machines', 3),
('MSEN', 5270, 'Materials Characterization for Engineering', 3),
('MSEN', 5370, 'Materials Thermodynamics and Kinetics', 3),
('MSEN', 5430, 'Transmission Electron Microscopy in Materials Science & Engineering', 3),
('MSEN', 5470, 'Materials Composition and Structure', 3),

('MCEN', 1024, 'Chemistry for Energy and Materials Science', 3),
('MCEN', 1025, 'Computer-Aided Design and Fabrication', 4),
('MCEN', 2000, 'Mechanical Engineering as a Profession', 1),
('MCEN', 2023, 'Statics and Structures', 3),
('MCEN', 2024, 'Materials Science', 3),
('MCEN', 2043, 'Dynamics', 3),
('MCEN', 2063, 'Mechanics of Solids', 3),
('MCEN', 3012, 'Thermodynamics', 3),
('MCEN', 3017, 'Circuits and Electronics', 3),
('MCEN', 3021, 'Fluid Mechanics', 3),
('MCEN', 3022, 'Heat Transfer', 3),
('MCEN', 3025, 'Component Design', 3),
('MCEN', 3030, 'Computational Methods', 3),
('MCEN', 3032, 'Thermodynamics 2', 3),
('MCEN', 3047, 'Data Analysis and Experimental Methods', 4),
('MCEN', 3930, 'Mechanical Engineering Cooperative Education', 6),
('MCEN', 4010, 'Microsystems Integration', 3),
('MCEN', 4012, 'Renewable Fuels, Fuel Cells and Internal Combustion Engines', 3),
('MCEN', 4026, 'Manufacturing Processes and Systems', 3),
('MCEN', 4032, 'Sustainable Energy', 3),
('MCEN', 4043, 'System Dynamics', 3),
('MCEN', 4045, 'Mechanical Engineering Design Project 1', 3),
('MCEN', 4057, 'Environmental Modeling', 3),
('MCEN', 4064, 'Soft Machines', 3),
('MCEN', 4085, 'Mechanical Engineering Senior Design Project 2', 3),
('MCEN', 4086, 'Writing for Design Projects', 1),
('MCEN', 4113, 'Mechanics of Cancer', 3),
('MCEN', 4117, 'Anatomy and Physiology for Engineers', 3),
('MCEN', 4123, 'Vibration Analysis', 3),
('MCEN', 4124, 'Mechanical Behavior of Materials', 3),
('MCEN', 4125, 'Optimal Design', 3),
('MCEN', 4127, 'Biomedical Ultrasound', 3),
('MCEN', 4131, 'Air Pollution Control Engineering', 3),
('MCEN', 4133, 'Intro to Tissue Biomechanics', 3),
('MCEN', 4135, 'Wind Energy and Wind Turbine Design', 3),
('MCEN', 4137, 'Anatomy and Physiology 2', 3),
('MCEN', 4138, 'Feedback Control', 3),
('MCEN', 4141, 'Indoor Air Pollution', 3),
('MCEN', 4151, 'Flow Visualization', 3),
('MCEN', 4152, 'Introduction to Combustion', 3),
('MCEN', 4154, 'Biocolloids and Biomembranes', 3),
('MCEN', 4155, 'Automated Mechanical Design Synthesis', 3),
('MCEN', 4157, 'Modeling of Human Movement', 3),
('MCEN', 4162, 'Energy Conversion', 3),
('MCEN', 4171, 'Biofluids on the Micro Scale', 3),
('MCEN', 4173, 'Finite Element Analysis', 3),
('MCEN', 4174, 'Failure of Engineering Materials', 3),
('MCEN', 4183, 'Mechanics of Composite Materials', 3),
('MCEN', 4194, 'Electrochemical Energy Conversion and Storage', 3),
('MCEN', 4195, 'Bioinspired Robotics', 3),
('MCEN', 4238, 'Design for Community', 3),
('MCEN', 4279, 'Aesthetics in Design', 3),
('MCEN', 4292, 'Materials and Devices in Medicine', 3),
('MCEN', 4293, 'Mechanics of Soft Matter', 3),
('MCEN', 4298, 'Introduction to Polymers', 3),
('MCEN', 4299, 'Household Energy Systems', 3),
('MCEN', 4700, 'Quantum Forge I', 3),
('MCEN', 4710, 'Quantum Forge II', 3),
('MCEN', 5010, 'Microsystems Integration', 3),
('MCEN', 5012, 'Renewable Fuels, Fuel Cells and Internal Combustion Engines', 3),
('MCEN', 5014, 'Energy Materials Characterization', 3),
('MCEN', 5020, 'Methods of Engineering Analysis 1', 3),
('MCEN', 5021, 'Introduction to Fluid Dynamics', 3),
('MCEN', 5022, 'Classical Thermodynamics', 3),
('MCEN', 5023, 'Solid Mechanics 1', 3),
('MCEN', 5024, 'Materials Chemistry and Structures', 3),
('MCEN', 5027, 'Graduate Seminar', 1),
('MCEN', 5032, 'Sustainable Energy', 3),
('MCEN', 5034, 'Thermodynamics of Materials', 3),
('MCEN', 5040, 'Methods of Engineering Analysis 2', 3),
('MCEN', 5041, 'Advanced Fluid Mechanics 1', 3),
('MCEN', 5042, 'Heat Transfer', 3),
('MCEN', 5044, 'Mechanical Behavior of Materials', 3),
('MCEN', 5045, 'Design for Manufacturability', 3),
('MCEN', 5055, 'Advanced Product Design', 3),
('MCEN', 5057, 'Environmental Modeling', 3),
('MCEN', 5064, 'Soft Machines', 3),
('MCEN', 5065, 'Graduate Design I', 3),
('MCEN', 5075, 'Graduate Design II', 3),
('MCEN', 5113, 'Mechanics of Cancer', 3),
('MCEN', 5115, 'Mechatronics and Robotics I', 3),
('MCEN', 5117, 'Anatomy and Physiology for Engineers', 3),
('MCEN', 5121, 'Compressible Flow', 3),
('MCEN', 5122, 'Statistical Thermodynamics', 3),
('MCEN', 5125, 'Optimal Design', 3),
('MCEN', 5127, 'Biomedical Ultrasound', 3),
('MCEN', 5131, 'SemAir Pollution Control Engineeringinar', 3),
('MCEN', 5133, 'Intro to Tissue Biomechanics', 3),
('MCEN', 5135, 'Wind Energy and Wind Turbine Design', 3),
('MCEN', 5137, 'Anatomy and Physiology 2', 3),
('MCEN', 5138, 'Feedback Control', 3),
('MCEN', 5141, 'Indoor Air Pollution', 3),
('MCEN', 5147, 'Mechanobiology', 3),
('MCEN', 5151, 'Flow Visualization', 3),
('MCEN', 5152, 'Introduction to Combustion', 3),
('MCEN', 5153, 'Introduction to Fracture Mechanics', 3),
('MCEN', 5154, 'Biocolloids and Biomembranes', 3),
('MCEN', 5155, 'Automated Mechanical Design Synthesis', 3),
('MCEN', 5157, 'Modeling of Human Movement', 3),
('MCEN', 5161, 'Aerosols', 3),
('MCEN', 5171, 'Biofluids on the Micro Scale', 3),
('MCEN', 5173, 'Finite Element Analysis', 3),
('MCEN', 5174, 'Failure of Engineering Materials', 3),
('MCEN', 5183, 'Mechanics of Composite Materials', 3),
('MCEN', 5194, 'Electrochemical Energy Conversion and Storage', 3),
('MCEN', 5185, 'Bioinspired Robotics', 3),
('MCEN', 5255, 'Design for Mfg', 3),
('MCEN', 5279, 'Aesthetics in Design', 3),
('MCEN', 5292, 'Materials and Devices in Medicine', 3),
('MCEN', 5293, 'Mechanics of Soft Matter', 3),
('MCEN', 5298, 'Introduction to Polymers', 3),
('MCEN', 5299, 'Household Energy Systems', 3),
('MCEN', 5448, 'Linear Systems', 3),
('MCEN', 5488, 'Geometric Control Theory', 3),
('MCEN', 5498, 'Stochastic Control Theory', 3),
('MCEN', 5636, 'Micro-Electro-Mechanical Systems 1', 3),
('MCEN', 6001, 'Reacting Flows', 3),
('MCEN', 6184, 'Structure and Properties of Polymers', 3),
('MCEN', 7221, 'Turbulence', 3);

INSERT INTO user_courses (username, course_prefix, course_id, grade_complete) VALUES 
('asd', 'CSCI', 1000, 4.0),
('asd', 'CSCI', 1300, 3.0);